# Generated by Django 5.1.1 on 2024-09-25 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fein', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, choices=[('restaurants', 'Restaurants'), ('stores', 'Stores'), ('wholesale', 'Wholesale'), ('services', 'Services')], max_length=20, null=True)),
                ('workflow_stage', models.CharField(choices=[('new', 'New'), ('market_approved', 'Market Approved'), ('market_declined', 'Market Declined'), ('sales_approved', 'Sales Approved'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='api.business')),
            ],
        ),
    ]
